services:
  
  tasks-api:
    build: tasks-api/
    ports:
      - "8000:8000"
    depends_on:
      - upload-api

  upload-api:
    build: s3-storage/
    ports:
      - "5050:5050"
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
     - "9000:9000"
     - "9001:9001"
    environment:
     MINIO_ROOT_USER: testuser
     MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-storage:/data
    healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
     interval: 30s
     timeout: 20s
     retries: 3
  db:
    image: postgres:14.18-bookworm
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "passwd123!"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
volumes:
  minio-storage:
  postgres-data: